# Generated by Django 2.2.1 on 2019-05-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20190507_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='owner',
            new_name='user',
        ),
    ]
